package com.sc.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sc.entity.NetAddress;
import com.sc.entity.User;

import com.sc.greendao.dao.NetAddressDao;
import com.sc.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig netAddressDaoConfig;
    private final DaoConfig userDaoConfig;

    private final NetAddressDao netAddressDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        netAddressDaoConfig = daoConfigMap.get(NetAddressDao.class).clone();
        netAddressDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        netAddressDao = new NetAddressDao(netAddressDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(NetAddress.class, netAddressDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        netAddressDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public NetAddressDao getNetAddressDao() {
        return netAddressDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
